### PR TITLE
[Amazium version] Upgrades btn-group class name and Amazium version

### PR DESCRIPTION
**Pull request by MikeBallan**

### CODE REVIEW

**Comment by catchamonkey** [comment]
Nice one, thanks!

**Comment by MikeBallan** [comment]
Will need to update to the latest version when you have done the v5 release..!

**Comment by catchamonkey** [comment]
v5 just went stable so this can be updated 

https://github.com/OwlyStuff/amazium/releases/tag/v5.0.0

**Comment by MikeBallan** [comment]
@catchamonkey Have updated to the latest version of Amazium v5 so think we could put this live..! It has all the updated docs for Amazium also..!

**Review by catchamonkey — APPROVED** [review]
LGTM

**Pull request merged**
