### PR TITLE
[Templates] Fixed spelling and grammar.

### PR DESCRIPTION
**Pull request by graemechapman**
@MikeBallan @catchamonkey @shahrukhomar

### CODE REVIEW

**Comment by catchamonkey** [comment]
Thanks @graemechapman 
Do the label spelling fixes rely on a new version of amazium being published first?

**Comment by graemechapman** [comment]
@catchamonkey yes, it is based on changes in https://github.com/OwlyStuff/amazium/pull/70

**Comment by catchamonkey** [comment]
OK, once that is merged and a new release has been published, can you update this PR with the new requirement version of the library? Thanks.

**Comment by catchamonkey** [comment]
@graemechapman https://github.com/OwlyStuff/amazium/releases/tag/v4.0.0-beta.8

**Comment by catchamonkey** [comment]
I'll do an update and shrinkwrap in a separate PR, thanks.

**Pull request merged**
